[package]
name = "reem"
version = "0.1.0"
authors = ["Chad Nehemiah <chad.nehemiah94@gmail.com>"]
edition = "2018"

[workspace]
members = [
    ".",
    "api",
]

[dependencies]
reem-api = { path = "api/", version = "0.1.0"}