[package]
name = "gerrehbenta"
version = "0.1.0"
authors = ["Chad Nehemiah <chad.nehemiah94@gmail.com>"]
edition = "2018"


[dependencies]
anyhow = "1.0.79"
cfonts = "1.1.0"
chrono = "0.4.31"
clap = { version = "4.4.16", features = ["derive"] }
crossterm = "0.27.0"
ethers = "2.0.11"
futures = "0.3.30"
juniper = "0.15.12"
rand = { version = "0.7.3", default-features = false, features = ["std"] }
ratatui = "0.25.0"
serde = "1.0.194"
simplelog = "0.12.1"
tokio = { version = "1.35.1", features = ["full"] }
url = "2.5.0"
