[package]
name = "reem"
version = "0.1.0"
authors = ["Chad Nehemiah <chad.nehemiah94@gmail.com>"]
edition = "2018"


[dependencies]
crossterm = { version = "0.19" }
rand = { version = "0.7.3", default-features = false, features = ["std"] }
tui = { version = "0.14", default-features = false, features = ['crossterm'] }
