[package]
name = "gerrehbenta"
version = "0.1.0"
authors = ["Chad Nehemiah <chad.nehemiah94@gmail.com>"]
edition = "2018"


[dependencies]
cfonts = "1.1.0"
chrono = "0.4.31"
crossterm = "0.27.0"
ethers = "2.0.11"
rand = { version = "0.7.3", default-features = false, features = ["std"] }
ratatui = "0.25.0"
serde = "1.0.194"
tui-input = "0.8.0"
tuirealm = "1.9.1"
