[package]
name = "reem-api"
version = "0.1.0"
authors = ["Chad Nehemiah <chad.nehemiah94@gmail.com>"]
edition = "2018"
license = "MIT"
description = "API for reem"


[dependencies]
juniper = "0.15.3"
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"
